export const componentWidth: number = 32;
export const componentWidth3Quarters: number = 96;
export const componentWidthHalf: number = 64;
export const componentWidth125Percent: number = 170; // unchanged (semantic token)
export const componentGap: number = 8;
export const componentGapDouble: number = 16;
export const menuIconMargin: number = 6;
export const menuTextMargin: number = 20;
export const iconMarginAdjust: number = 6.5;
